### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by risturiz** [OSMLatam/status#1]
Test

**Comment by angoca** [comment]
Este es un incidente manual? o automático? en otras palabras, esta herramienta los crea si algo pasa?

**Comment by risturiz** [comment]
Hasta donde sé es manual... Y el action del Github lo refleja en el status... Me parece buen mecanismo para llevar todo lo relacionado que hagamos en la plataforma y las cosas que falten, etc... Los sistemas beta, anuncios de mantemiento.

P.D. Cierra este issue

**Comment by angoca** [comment]
Problema resuelto!
