### ISSUE TITLE
OpenDroneMap aún no se puede referenciar

### ISSUE THREAD

**Issue by angoca** [OSMLatam/status#2]
**Describe the bug**
Está en el servidor de Angoca en el puerto 8000

@risturiz qué podemos hacer?

**Comment by risturiz** [comment]
Voy a tratar de realizar el proceso nuevamente con el túnel... Inicialmente funcionaba hasta que le cambié el nombre xD

**Comment by angoca** [comment]
Listo, ya funciona: https://opendrone.osm.lat/
