### ISSUE TITLE
Migración de mail y vault

### ISSUE THREAD

**Issue by angoca** [OSMLatam/status#5]
*Nombre del componente*:
Mail

*Descripción de la situación anómala*:
El mail está funcionando, pero sigue apareciendo como caído.

*Comportamiento normal*:
Cargar la página de visualización de mail.

**Comment by angoca** [comment]
La url de visualización cambió como parte de la migración, ahora es webmail.

**Comment by risturiz** [comment]
El viejo vault ( vault.cloud.osm.lat ) fue desincorporado.
