### ISSUE TITLE
GeoServer no permite ciertas funcionalidades

### ISSUE THREAD

**Issue by angoca** [OSMLatam/status#7]
**Describe the bug**
Algunas operaciones como crear usuario, cambiar de página en un listado, entre otras opciones, no se permiten y se genera el error del pantallazo.

**To Reproduce**
1. Ir a la página de previsualización https://geoserver.osm.lat/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage?18&filter=false
2. Dar en página 2
3. No hace nada.

Otro caso
1. En usuarios y grupos, dar click en agregar usuario.

**Expected behavior**
Debería cambiar de páginas, o pasar a la página de agregar usuario.

**Screenshots**
If applicable, add screenshots to help explain your problem
![telegram-cloud-photo-size-1-5062540667363896425-y](https://github.com/OSMLatam/status/assets/294317/b8c96567-a8ef-4991-a020-2997614b4c4b)

Esto parece estar relacionado con la forma como el subdominio geoserver apunta al servidor de angoca.

**Comment by angoca** [comment]
De pronto este es el problema:

https://docs.geoserver.org/latest/en/user/security/webadmin/csrf.html

https://gis.stackexchange.com/questions/385106/unable-to-add-layer-to-geoserver-origin-does-not-correspond-to-request

**Comment by risturiz** [comment]
Una prueba sería -> setting GEOSERVER_CSRF_DISABLE to true in /var/lib/tomcat9/webapps/geoserver/WEB-INF/web.xml

**Comment by angoca** [comment]
Listo, solucionado!!!
